### PR TITLE
Support for `inet` data type.

### PR DESCRIPTION
**Pull request by rikvdkleij**
Created encoder and decoder for `inet`.

To expose the new (data) types I have created the module `Hasql.Data`.

### CODE REVIEW

**Comment by rikvdkleij** [comment]
@nikita-volkov
When will you review this PR?

**Comment by nikita-volkov** [comment]
Hi! Sorry for the delay. I'm on vacation. I'll review this in the coming week.

**Comment by rikvdkleij** [comment]
@nikita-volkov 
No problem, enjoy your holiday!

**Comment by rikvdkleij** [comment]
@nikita-volkov 
Don't forget this PR :smile:

**Pull request closed without merging**
