### PR TITLE
Add tested README getting started example

### LINKED ISSUE #98: tested, getting started example in README
Hey @nikita-volkov 

first of all, hats off for this library, I'm really enjoying its design for simplicity.

I really missed in the begining how to put the puzzles together, for a simple example to get started.  Would you mind if I make a PR to add something like https://github.com/well-typed/pretty-sop#example (which would be also a literate haskell and part of test-suites).

### PR DESCRIPTION
**Pull request by domenkozar**
Fixes #98 #99

### CODE REVIEW

**Comment by domenkozar** [comment]
@nikita-volkov CI passes now, it's not perfect, but it's a start. Let me know what you think.

**Comment by domenkozar** [comment]
Rendered: https://github.com/domenkozar/hasql/blob/tested-readme/README.md

**Comment by nikita-volkov** [comment]
There's a few mistakes there and I'll also like to apply a few corrections to the style. I'll build up on this some time soon. Thanks!

**Comment by domenkozar** [comment]
@nikita-volkov I wonder, why did you decide to revert the test of readme compiles? :)

**Pull request merged**
